name: CI
on:
  push:
    branches:
      - master
      - 'release/**'
  pull_request:
jobs:
  main:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
      - uses: actions/checkout@v3
        with:
          # https://github.com/reproducible-containers/repro-get/issues/3
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - run: go test -covermode=atomic -race -v ./...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.2.0
        with:
          version: v1.50.0
          args: --verbose
      - run: make integration
      - run: make && sudo make install
      - name: Smoke testing of 'repro-get dockerfile generate'
        run: repro-get --distro=debian dockerfile generate . debian:bullseye-20211220 gcc build-essential
        # TODO: run the examples with a fast, stable, and persistent file provider
